### ISSUE TITLE
Operator '>' cannot be applied to operands of type 'System.TimeSpan' and 'System.TimeSpan'

### ISSUE THREAD

**Issue by AndrewSav** [JaroslawWaliszko/ExpressiveAnnotations#63] opened 2015-06-23 06:58 UTC
I'm getting the following error message:

    Operator '>' cannot be applied to operands of type 'System.TimeSpan' and 'System.TimeSpan'

This is with a rule:

    [AssertThat("EndTime.Value > StartTime.Value")]
    virtual public TimeSpan? EndTime { get; set; }

Surely what error message says is not true and this operator *can* be applied to those operand types?

**Comment by JaroslawWaliszko** [comment] 2015-06-23 08:08
Hi,
In theory this operator can be applied to `TimeSpan`, but here you've just found a bug. It will be fixed soon.

Regards

**Comment by JaroslawWaliszko** [comment] 2015-06-23 13:31
Proposed solution here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/2bcc07598b8083a43c86ac736896521e40cb5b45

**Comment by JaroslawWaliszko** [comment] 2015-06-23 22:09
... client-side proposal done as well: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/a21ca410202bb5e51adb684a4a077324d4efdeb5

**Comment by AndrewSav** [comment] 2015-06-24 00:00
I'm curious. One can do something like this

```
using System;
using System.Linq.Expressions;

namespace OperatorOverloadTest
{
    class A
    {
        public int Value { get; set; }
    }

    class B
    {
        public int Value { get; set; }

        public static int operator +(A a, B b)
        {
            return a.Value + b.Value;
        }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            var a = Expression.Constant(new A { Value = 2 });
            var b = Expression.Constant(new B { Value = 3 });
            var result = Expression.Convert(Expression.Add(a, b), typeof(object));
            var lambda = Expression.Lambda<Func<object>>(result);
            var final = lambda.Compile()();
            // prints 5
            Console.WriteLine(final);
        }
    }
}
```

If we can do this, I'm wondering if you very nice library can do the same? That would be mighty helpful. You added these checks for `TimeSpan` in particular, but you can do so much more if you let the Expression engine try and process operators. I understand that in this way there is no easy and performance efficient way to report the errors, but may be you can thing something up?

**Comment by JaroslawWaliszko** [comment] 2015-06-24 00:25
I'll take a look at that idea within the next few days. For now, I have no idea how to wire it up. The problem is, that the logic should behave in consistent way at both server- and client- side. I'd like to avoid situations where expression at C# part gives different result when executed by JS engine, and vice versa. I'm trying to detect most potential problems at the parsing phase and protect users from hurting themselves if possible. That's why I cannot really use the entire power granted by Expresion Trees.

**Comment by AndrewSav** [comment] 2015-06-24 00:35
That's a pity. For my purposes I do not need the client side at all. On the server side something like this would work:

```c#
            string error;
            Expression result = TryProcessOperator(oper.Type, arg1, arg2, out error);
            if (result == null)
            {
                throw new ParseErrorException(
                       string.Format("Operator '{0}' cannot be applied to operands of type '{1}' and '{2}'.", oper.Value, arg1.Type, arg2.Type),
                       oper.Location);     
            }
            return result;
```

And then:

```
        private static Expression TryProcessOperator(TokenType t, Expression arg1, Expression arg2, out string error)
        {
            error = null;
            try
            {
                switch (t)
                {
                    case TokenType.LT:
                        return Expression.LessThan(arg1, arg2);
                    case TokenType.LE:
                        return Expression.LessThanOrEqual(arg1, arg2);
                    case TokenType.GT:
                        return Expression.GreaterThan(arg1, arg2);
                    case TokenType.GE:
                        return Expression.GreaterThanOrEqual(arg1, arg2);
                    case TokenType.EQ:
                        return Expression.Equal(arg1, arg2);
                    case TokenType.NEQ:
                        return Expression.NotEqual(arg1, arg2);
                    default:
                        throw new ArgumentOutOfRangeException(); // never gets here
                } 
            }
            catch (InvalidOperationException ex)
            {
                error = ex.Message;
                return null;
            }
        }
```

**Comment by AndrewSav** [comment] 2015-06-24 00:40
May be we could add an option to support more on the server at the expense of client-side incompatibility?

**Comment by JaroslawWaliszko** [comment] 2015-06-24 10:54
Thank you for suggestion.

When it comes to the flag (let's call it *CompatibilityMode*) for switching between *server-and-client* protective parsing, to *server-only* powerful one - it is good idea. For sure it would help to detect  some fragile expressions to the users, pointing out warnings [briefly mentioned in this section](https://github.com/JaroslawWaliszko/ExpressiveAnnotations#traps). Downside is that such change is probably quite demanding in terms of time needed for correct implementation.

When it comes to your code snippet - the drawback is, as you've already noticed, that error messages will not be accurate enough. Since passing arguments to Expression Tree library is the late stage of computation, some of the arguments are already implicitly converted to preserve types compatibility, etc. Because of that, if the suggested change is applied, sample expression like `0 + null`, will rise the following error:
```
Parse error on line 1, column 3:
... + null ...
    ^-- The binary operator Add is not defined for the types 'System.Double' and 'System.Object'
```
instead of current one (more correct IMHO):
```
Parse error on line 1, column 3:
... + null ...
    ^-- Operator '+' cannot be applied to operands of type 'System.Int32' and 'null'
```

(at ExpressiveAnnotations.Tests.ParserTest.verify_various_parsing_errors() in ParserTest.cs: line 814)

My kind proposal for you, at least for now - since it can take some time for me to decide what to do with that ideas, is to fork the repository and modify it according to your needs. Thereby you will not be blocked by me and dependent on some overdue changes.

I'd like to avoid situation where users are allowed to write more complicated expressions without any protection, which could result in hard-to-detect errors at the browser side.

**Comment by AndrewSav** [comment] 2015-06-24 13:43
This is fair enough. If I needed that advanced functionality I would try and do just that. Fortunately (or unfortunately) your fix mostly covers it for me so I'll leave this exercise for another time. (Which is just another way of saying most likely never =). You on the other hand can file this under "possible future improvements" if that's something that might interest you at all. Thank you again for your time and for your prompt responses. For me this issue is resolved now.

**Comment by JaroslawWaliszko** [comment] 2015-06-24 14:42
Thanks,
I'm glad I could be so far at least partially helpful.

Regards

**Closed by JaroslawWaliszko** 2015-06-24 14:42 UTC
Labels: bug, enhancement

**Comment by jwaliszko** [comment] 2016-07-10 19:33
Issue is long outdated, but to preserve cohesion there is an update to this thread - EA respects now all the overloaded operators (Expression library is not restricted - see https://github.com/jwaliszko/ExpressiveAnnotations/commit/96b5caa2d17b5d1bf1cf81a1054950332a65383d). The error printing functionality is still working as expected. 

Another reason for this change - we support `ValueParser` attributes since some time, so at client-side we can construct any type we want, e.g. we can prepare respective value of such a type which will be accepted by particular operators as well.

**Comment by AndrewSav** [comment] 2016-07-10 20:27
@jwaliszko cheers!
